### ISSUE TITLE
Implement number lines

### ISSUE THREAD

**Issue by jeffuong** [jeffuong/Axolotl#2]
Normally text editors have line numbers for editors to easily navigate to

This is an example of what this feature would look like
![image](https://app.gitkraken.com/api/glo/boards/5c1edbd5fef389000fe0943d/attachments/5c1ee2ccfef389000fe095a5)

**Comment by Erctrn** [comment]
#9 Working on feature, still has error and working on a solution for it.

**Comment by Erctrn** [comment]
Issue solved on #9
