### ISSUE TITLE
Fix dll issue

### ISSUE THREAD

**Issue by jeffuong** [jeffuong/Axolotl#3]
Currently on windows. There's an issue where we don't copy dlls over while building the project. As a visual studio user, it's annoying to copy and paste the dlls over one at a time when cleaning out the build folder.

Find the correct dlls and copy them in the correct location of the build folder using CMake commands.
Currently these dlls are

Qt5Guid.dll
Qt5PrintSupportd.dll
Qt5Widgetsd.dll
Qt5Cored.dll

Make sure to do it for the release versions too with their corresponding release dlls

**Comment by Erctrn** [comment]
Fixed here #24
